version: '3.7'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test_ap
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "mysql+pymysql://root:123456@db:3306/test_ap"
    depends_on:
      - db

volumes:
  db_data:
